import pandas as pd
import re
import typing
from pathlib import Path
import logging
import argparse

"""
Script to preprocess organisation names derived from KVK Handelsregister.
This makes sure multiple variants of organisation names are included in the blacklist,
while clearing out organisation names that would create too many false positives.

Purpose
-------
Expand KVK organisation names by generating common legal entity variants (B.V., N.V., V.O.F., etc.)
and removing noisy entries. Output is suitable for use as a blacklist in ListAnonymizer.
Filters out entries that are too short, contain only initials, or match the whitelist.

Usage (CLI)
-------
$ python -m anonymizer.helpers.kvk_preprocessing raw_kvk_file.csv "src/anonymizer/input_files/Whitelist Basic.xlsx"

Available CLI Options
-------
positional arguments:
  kvk-path              Path to KVK Handelsregister CSV file (semicolon-separated).
                        Expected columns: 'Bedrijfsnaam', 'Handelsnaam 1-5'
  
  whitelist-path        Path to whitelist Excel file (e.g., src/anonymizer/input_files/Whitelist\ Basic.xlsx).
                        Used to exclude organisation names that should never be masked.
                        Sheet name: 'List', Column name: 'List'

optional arguments:
  --output-path OUTPUT_PATH
                        Path to output Excel file with processed organisation names.
                        Default: 'results/kvk_processed.xlsx'
                        Output columns: 'List' (processed name), 'KVK' (original name), 'Case Sensitive'

Output Format
-------
The output Excel file contains three columns:
  
  List              Processed organisation name variant (ready for ListAnonymizer blacklist)
  KVK               Original unmodified KVK organisation name
  Case Sensitive    0 = case-insensitive matching (restaurants/cafés)
                    1 = case-sensitive matching (other entities)

Processing Rules
-------
• Extracts and generates variants of legal entity suffixes:
  - B.V./BV (Besloten Vennootschap)
  - N.V./NV (Naamloze Vennootschap)
  - V.O.F./VOF (Vennootschap onder Één Firma)
  - V.V.E./VVE/Vereniging van eigenaren (Homeowners association)

• Removes entries that are:
  - Shorter than 4 characters
  - Contain only initials or punctuation
  - Present in the whitelist

• Sets restaurants/cafés as case-insensitive for better recall

Examples
-------
# Basic usage with default output location:
$ python -m anonymizer.helpers.kvk_preprocessing kvk_handelsregister.csv src/anonymizer/input_files/Whitelist\ Basic.xlsx

# Custom output path:
$ python -m anonymizer.helpers.kvk_preprocessing kvk_handelsregister.csv src/anonymizer/input_files/Whitelist\ Basic.xlsx \
  --output-path data/my_kvk_names.xlsx

Usage (module)
-------
from anonymizer.helpers import kvk_preprocessing
import pandas as pd

kvk_names = pd.read_csv('raw_kvk_file.csv', sep=';')
whitelist = pd.read_excel('src/anonymizer/input_files/Whitelist Basic.xlsx', sheet_name='List')['List'].str.lower()

kvk_preprocessing.run(kvk_names, whitelist.tolist(), output_path="kvk_processed.xlsx")
"""

LOGGER = logging.getLogger(__name__)
logging.basicConfig(format="[%(levelname)s] %(message)s", level=logging.INFO)

BASE_DIR = Path(__file__).resolve().parent

RE_NO_LETTERS_OR_INITIALS = re.compile(r'^(?:[^A-Za-z]*|(?:[A-Za-z]\.\s*){1,3})$')
RE_BV = re.compile(r'(?:^B\.V\.(?=\s)|(?<=\s)B\.V\.$)')
RE_NV = re.compile(r'(?:^N\.V\.(?=\s)|(?<=\s)N\.V\.$)')
RE_VOF = re.compile(r'(?:^V\.O\.F\.(?=\s)|(?<=\s)V\.O\.F\.$)')
RE_VVE = re.compile(r'^(?:v\.v\.e\.|vve|vereniging van (?:eigenaren|eigenaars))(?=\s+)', re.IGNORECASE)
RE_VARIANTS = {
    'B.V.': (RE_BV, ['B.V.', 'BV']),
    'N.V.': (RE_NV, ['N.V.', 'NV']),
    'V.O.F.': (RE_VOF, ['V.O.F.', 'VOF']),
    'VVE': (RE_VVE, ['V.V.E.', 'VVE', 'VvE', 'Vereniging van eigenaren', 'Vereniging van eigenaars'])
    }

RE_RESTAURANTS = re.compile(r'restaurant|café|cafe', re.IGNORECASE)

def run(kvk_names: pd.DataFrame, whitelist: list, output_path: str):
    """
    Docstring for run
    
    :param kvk_names: Input Dataframe with KVK Handelsregister names
    :type kvk_names: pd.DataFrame
    :param whitelist: Names to whitelist (case insensitive)
    :type whitelist: list
    :param output_path: Path to output file to be generated by this script
    :type output_path: str
    """
    
    whitelist = [o.strip().lower() for o in whitelist]
    cols = ['Bedrijfsnaam', 'Handelsnaam 1', 'Handelsnaam 2', 'Handelsnaam 3', 'Handelsnaam 4', 'Handelsnaam 5']
    unique_names = pd.DataFrame(
        kvk_names[cols]
        .stack()
        .dropna()
        .drop_duplicates()
        .dropna()
        .reset_index(drop=True),
        columns=['List']
    )
    unique_names['Case Sensitive'] = unique_names['List'].apply(lambda x: 0 if re.search(RE_RESTAURANTS, x) else 1) # Make restaurant names case insensitive, everything else is case sensitive
    unique_names.head()

    unique_names_extended = (
        unique_names
        .assign(name_variants=unique_names['List'].map(lambda x: _clean_names(x, whitelist)))
        .explode('name_variants', ignore_index=True)
        .dropna(subset='name_variants')
        .drop_duplicates(subset='name_variants')
        .rename(columns={'List': 'KVK', 'name_variants': 'List'})
    )

    with pd.ExcelWriter(
        output_path,
        engine="xlsxwriter",
        engine_kwargs={"options": {"strings_to_formulas": False}}
    ) as writer:
        unique_names_extended[['List', 'KVK', 'Case Sensitive']].to_excel(writer, index=False)

def _clean_names(raw_name: str, whitelist: list) -> list:
    """
    Clean the raw KVK names and return a processed list.

    :param raw_name: KVK name to be processed
    :type raw_name: str
    :param whitelist: Whitelist with names to be kept out. Should be lowercase.
    :type whitelist: list
    """
    cleaned_names = []
    for _ent, tup in RE_VARIANTS.items():
        re_match = re.search(tup[0], raw_name)
        if re_match:
            if re_match.span()[0] == 0: # Match was at start of string
                base_name = raw_name[re_match.span()[1]:]
                if base_name.strip().lower() in whitelist: # Ignore names in the whitelist
                    continue
                cleaned_names.append(base_name.strip()) # Add the base name without legal denomination
                for var in tup[1]: # Create a name containing all variants of the legal denomination
                    cleaned_names.append(var+ base_name)
            else: # Match was at end of string
                base_name = raw_name[:re_match.span()[0]]
                if base_name.strip().lower() in whitelist: # Ignore names in the whitelist
                    continue
                cleaned_names.append(base_name.strip()) # Add the base name without legal denomination
                for var in tup[1]: # Create a name containing all variants of the legal denomination
                    cleaned_names.append(base_name + var)
    if not cleaned_names: # No legal denomination was found
        cleaned_names.append(raw_name)

    # Delete names that contain no letters, look like someone's initials, are shorter than 4 characters or are in the whitelist
    cleaned_names_shortlist = []
    for n in cleaned_names:
        if (
            not re.fullmatch(RE_NO_LETTERS_OR_INITIALS, n) 
            and not len(n) < 4
            and not n.lower() in whitelist
        ):
            cleaned_names_shortlist.append(n)
    
    return cleaned_names_shortlist

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("kvk_path", type=Path, help="KVK Handelsregister csv-file")
    parser.add_argument("whitelist_path", type=Path, help=".xlsx with whitelist (e.g. src/anonymizer/input_files/Whitelist Basic.xlsx)")
    parser.add_argument("--output-path", default="results/kvk_processed.xlsx")
    args = parser.parse_args()

    LOGGER.info("Loading %s ...", args.kvk_path)
    kvk_names = pd.read_csv(args.kvk_path, sep=';')

    LOGGER.info("Loading %s ...", args.whitelist_path)
    whitelist = pd.read_excel(args.whitelist_path, sheet_name='List')['List'].str.lower()

    LOGGER.info("Writing output file → %s", args.output_path)
    run(kvk_names, whitelist, output_path=args.output_path)

    LOGGER.info("Done.")


if __name__ == "__main__":
    main()